#!/bin/bash

# This script will install IPFS software and establish initial settings.
# This must be executed with root privileges or with sudo.

if [[ $(id -u) -ne 0 ]] ; then echo "Please run as root, or prefix with 'sudo'" ; exit 1 ; fi

WAIT=0                               # Set to 1 to wait fo confirmation to continue each step

CONFIG=/home/ipfs/.ipfs/config       # IPFS configuration file

if [ "$1" != "" ]; then              # Was a command line parameter provided?
  if ! [ -z "${1//[0-9]}" ]          # Yes. Was it a positive number?
  then                               # No. Print error and exit
    echo "Please enter a positive integer for StorageMax parameter (gigabytes)"
    exit 1
  else                               # Command line parameter overrides default storageMax
    STORAGE_MAX="$1G"
  fi
else                                 # No command line parameter, so calculate storageMax
  FREE=`df --output=avail -B 1 / | tail -n 1` # Free space in bytes on root partition
  MAX=`expr $FREE / 1320000000`      # Approximately 75% of free space (in GB)
  printf -v STORAGE_MAX %dG $MAX     # Format the StorageMax parameter value
fi

if [ ! -f updated ]; then
  # Make sure the system is fully updated
  echo "Updating the OS (Operating System). When the popup appears, acknowledge it..."
  apt-get -y update && apt-get -y upgrade
  echo ""
  echo "The system needs to reboot. Afterwards, log back in and rerun this script."
  read -n 1 -p " Press any key to reboot..." key
  touch updated
  reboot
fi

if [ ! -e /etc/apt/sources.list.d/siderus.list ]; then
  echo "Installing credentials for siderus software repository..."
  apt install -y apt-transport-https curl
  curl https://get.siderus.io/key.public.asc | apt-key add -
  echo "deb https://get.siderus.io/ apt/" | tee -a /etc/apt/sources.list.d/siderus.list
  apt update
  echo ""
  if [ $WAIT == 1 ]; then read -n 1 -p "Press ^C to exit, any other key to proceed..." key; fi
fi

echo "Installing IPFS and supporting packages..."
apt-get -y install ipfs tmux ufw
apt -y autoremove
echo ""
if [ $WAIT == 1 ]; then read -n 1 -p "Press ^C to exit, any other key to proceed..." key; fi

echo "Opening required firewall ports..."
ufw allow 4001/tcp
ufw allow 22/tcp
echo ""
if [ $WAIT == 1 ]; then read -n 1 -p "Press ^C to exit, any other key to proceed..." key; fi

echo "Creating the ipfs user account and initializing IPFS..."
useradd -m -s /bin/bash ipfs
mkdir /home/ipfs/.ipfs
chown -R ipfs.ipfs /home/ipfs
runuser -l ipfs -c 'ipfs init > ~/.ipfs/init.log 2>&1'   # Initialize IPFS and log output
echo ""
if [ $WAIT == 1 ]; then read -n 1 -p "Press ^C to exit, any other key to proceed..." key; fi

echo "Setting maximum IPFS storage to $STORAGE_MAX in config file..."
sed -i "s/^\s*\"StorageMax.*$/    ~StorageMax~: ~$STORAGE_MAX~,/g" $CONFIG
sed -i "s/~/\"/g" $CONFIG
echo ""
if [ $WAIT == 1 ]; then read -n 1 -p "Press ^C to exit, any other key to proceed..." key; fi

echo "Creating SystemD unit to start IPFS on reboot..."
(
cat <<SYSD_UNIT
[Unit]
Description=IPFS daemon
After=network.target

[Service]
User=ipfs
LimitNOFILE=65536
Environment="IPFS_FD_MAX=4096"
Environment="IPFS_PATH=/home/ipfs/.ipfs"
ExecStart=/usr/bin/ipfs daemon --enable-namesys-pubsub
Restart=on-failure

[Install]
WantedBy=multi-user.target
SYSD_UNIT
) > /etc/systemd/system/ipfs.service

systemctl enable ipfs
systemctl start ipfs

echo "IPFS is now installed on this system."
